### ISSUE TITLE
Doc: print versus memory

### ISSUE THREAD

**Issue by candlerb** [pierky/pmacct-to-elasticsearch#16]
In [CONFIGURATION.md](https://github.com/pierky/pmacct-to-elasticsearch/blob/master/CONFIGURATION.md) it says:

> For "print" plugins, a crontab job is needed to run pmacct client and to redirect its output to pmacct-to-elasticsearch; for "memory" plugins the pmacct daemon can directly execute pmacct-to-elasticsearch.

However that is contradicted by the examples which follow.  They show a cronjob querying the memory plugin (`pmacct -p /var/spool/pmacct/my_mem.pipe`), and the print plugin using `print_trigger_exec` to run p2es.

Has the first paragraph got print and memory the wrong way round?

**Comment by pierky** [comment]
Thanks for pointing that out, indeed the right explaination is the longer one reported here https://github.com/pierky/pmacct-to-elasticsearch/blob/master/CONFIGURATION.md#plugins-configuration
Fixed!
