### ISSUE TITLE
Getting 401 Unauthorized access when posting data to ES !

### ISSUE THREAD

**Issue by gugansankar** [pierky/pmacct-to-elasticsearch#2]
Hi, I'm trying to post the data to ES using this pmacct-to-elasticsearch option. But getting "401 Unauthorized access" . Since the basic authentication enabled in my ES setup.

Does pmacct-to-elasticsearch have an option to include the authentication in the configuration file?

I couldn't find any option from the configuration guide : https://github.com/pierky/pmacct-to-elasticsearch/blob/master/CONFIGURATION.md

**Comment by pierky** [comment]
Hello,

could you test the new branch [esauth](https://github.com/pierky/pmacct-to-elasticsearch/commit/87adcb2d39dfa8dbb069327069d2646ad7d5c706)? I introduced HTTP basic/digest authentication support. I tested the basic authentication with ElasticSearch 1.5.2 and [Shield](https://www.elastic.co/products/shield) and it seems working fine.

Please let me know if it's ok so I'll merge it into master and build a new release.

**Comment by pierky** [comment]
Feature added in [v0.2.0](https://github.com/pierky/pmacct-to-elasticsearch/releases/tag/v0.2.0)
